"""Expand MaintQA dataset to 20 items

Manually annotated based on GJB 368B and GJB 451B
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.data.maintqa_builder import MaintQADataset, MaintQAItem, AnswerSource

# Original 5 items + 15 new items = 20 items
items = [
    # === Original 5 items ===
    MaintQAItem(
        id="maintqa_access_001",
        query="What is the minimum requirement for maintenance passage width?",
        query_en="What is the minimum maintenance passage width requirement?",
        constraint_type="Accessibility",
        constraint_type_id=1,
        answer="500mm",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="easy",
        equipment_types=["aircraft_engine", "naval_power"],
        keywords=["accessibility", "passage", "width"],
    ),
    MaintQAItem(
        id="maintqa_access_002",
        query="What is the minimum requirement for hand-access clearance?",
        query_en="What is the minimum hand reach gap requirement?",
        constraint_type="Accessibility",
        constraint_type_id=1,
        answer="50 mm (finger operation) or 100 mm (tool operation)",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="easy",
        equipment_types=["aircraft_engine"],
        keywords=["accessibility", "clearance"],
    ),
    MaintQAItem(
        id="maintqa_time_001",
        query="What is the definition of MTTR?",
        query_en="What is the definition of MTTR?",
        constraint_type="Time Parameters",
        constraint_type_id=10,
        answer="Mean Time To Repair — the average time required from the start of maintenance to restoration of normal operating condition after a product failure",
        answer_source=AnswerSource(document="GJB 368B", section="§3.1"),
        difficulty="easy",
        equipment_types=["aircraft_engine", "naval_power"],
        keywords=["MTTR", "definition"],
    ),
    MaintQAItem(
        id="maintqa_diag_001",
        query="What is the requirement for the fault detection rate (FDR)?",
        query_en="What is the requirement for FDR?",
        constraint_type="Diagnostic Parameters",
        constraint_type_id=11,
        answer="≥ 95% (typical value)",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.1"),
        difficulty="medium",
        equipment_types=["aircraft_engine"],
        keywords=["FDR", "fault detection rate"],
    ),
    MaintQAItem(
        id="maintqa_ergo_001",
        query="What is the maximum weight limit for an LRU?",
        query_en="What is the maximum weight limit for LRU?",
        constraint_type="Ergonomics",
        constraint_type_id=6,
        answer="≤ 25 kg (general requirement)",
        answer_source=AnswerSource(document="DOD-HDBK-791", section="§3.5"),
        difficulty="medium",
        equipment_types=["aircraft_engine"],
        keywords=["LRU", "weight"],
    ),
    # === 15 new items ===
    MaintQAItem(
        id="maintqa_inter_001",
        query="What are the basic requirements for interchangeability design?",
        query_en="What are the basic requirements for interchangeability design?",
        constraint_type="Interchangeability",
        constraint_type_id=2,
        answer="Interfaces of similar components shall be unified, with standard parts preferred",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="easy",
        equipment_types=["aircraft_engine", "naval_power"],
        keywords=["interchangeability", "standardization"],
    ),
    MaintQAItem(
        id="maintqa_error_001",
        query="What does error-proofing design include?",
        query_en="What does error-proofing design include?",
        constraint_type="Error-proofing",
        constraint_type_id=3,
        answer="Mis-insertion prevention design, identification markings, and color-coded labels",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="medium",
        equipment_types=["aircraft_engine"],
        keywords=["error-proofing", "mis-insertion prevention"],
    ),
    MaintQAItem(
        id="maintqa_safety_001",
        query="What are the requirements for maintenance safety design?",
        query_en="What are the maintenance safety design requirements?",
        constraint_type="Maintenance Safety",
        constraint_type_id=4,
        answer="Warning signs for high-temperature/high-pressure zones and protective device interlocks",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="medium",
        equipment_types=["aircraft_engine", "naval_power"],
        keywords=["maintenance safety", "warning"],
    ),
    MaintQAItem(
        id="maintqa_diag_002",
        query="What is the typical requirement for the fault isolation rate (FIR)?",
        query_en="What is the typical requirement for FIR?",
        constraint_type="Diagnostic Parameters",
        constraint_type_id=11,
        answer="≥ 90%",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.1"),
        difficulty="easy",
        equipment_types=["aircraft_engine"],
        keywords=["FIR", "fault isolation rate"],
    ),
    MaintQAItem(
        id="maintqa_ergo_002",
        query="What is the maximum limit for manual operating force?",
        query_en="What is the maximum manual operating force?",
        constraint_type="Ergonomics",
        constraint_type_id=6,
        answer="≤ 200N",
        answer_source=AnswerSource(document="DOD-HDBK-791", section="§3.5"),
        difficulty="easy",
        equipment_types=["aircraft_engine"],
        keywords=["operating force", "human factors engineering"],
    ),
    MaintQAItem(
        id="maintqa_repair_001",
        query="What is the principle of component repairability design?",
        query_en="What is the principle of component repairability design?",
        constraint_type="Repairability",
        constraint_type_id=7,
        answer="Repairable design shall be preferred; the repairable proportion of critical components shall be ≥ 70%",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="medium",
        equipment_types=["aircraft_engine", "naval_power"],
        keywords=["repairability"],
    ),
    MaintQAItem(
        id="maintqa_reduce_001",
        query="What design measures reduce maintenance content?",
        query_en="What are the design measures to reduce maintenance content?",
        constraint_type="Reduced Maintenance",
        constraint_type_id=8,
        answer="Maintenance-free design, automatic lubrication, and no periodic recalibration",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="medium",
        equipment_types=["aircraft_engine"],
        keywords=["reduced maintenance", "maintenance-free"],
    ),
    MaintQAItem(
        id="maintqa_skill_001",
        query="What is the design principle for reducing maintenance skill requirements?",
        query_en="What is the design principle for reducing maintenance skill requirements?",
        constraint_type="Reduced Skill",
        constraint_type_id=9,
        answer="Field-replaceable units require no special tools; disassembly/assembly steps ≤ 15",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="medium",
        equipment_types=["aircraft_engine"],
        keywords=["maintenance skill", "special tools"],
    ),
    MaintQAItem(
        id="maintqa_time_002",
        query="What is the definition of MTBF?",
        query_en="What is the definition of MTBF?",
        constraint_type="Time Parameters",
        constraint_type_id=10,
        answer="Mean Time Between Failures — the average operating time between two consecutive failures",
        answer_source=AnswerSource(document="GJB 368B", section="§3.1"),
        difficulty="easy",
        equipment_types=["aircraft_engine", "naval_power"],
        keywords=["MTBF", "definition"],
    ),
    MaintQAItem(
        id="maintqa_prev_001",
        query="What is the requirement for the preventive maintenance man-hour ratio?",
        query_en="What is the requirement for preventive maintenance ratio?",
        constraint_type="Preventive Maintenance",
        constraint_type_id=12,
        answer="Preventive maintenance man-hours shall be ≤ 40% of total maintenance man-hours",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.1"),
        difficulty="medium",
        equipment_types=["aircraft_engine"],
        keywords=["preventive maintenance", "man-hour ratio"],
    ),
    MaintQAItem(
        id="maintqa_access_003",
        query="What is the definition of maintainability?",
        query_en="What is the definition of maintainability?",
        constraint_type="Accessibility",
        constraint_type_id=1,
        answer="The ability of a product to be retained in or restored to a specified condition, when maintenance is performed under specified conditions and within a specified time, using prescribed procedures and resources",
        answer_source=AnswerSource(document="GJB 451B", section="§6.1"),
        difficulty="easy",
        equipment_types=["aircraft_engine", "naval_power", "armored_vehicle"],
        keywords=["maintainability", "definition"],
    ),
    MaintQAItem(
        id="maintqa_diag_003",
        query="What is the definition of BIT?",
        query_en="What is the definition of BIT?",
        constraint_type="Diagnostics",
        constraint_type_id=5,
        answer="Built-In Test — the fault detection and isolation capability integral to the equipment itself",
        answer_source=AnswerSource(document="GJB 451B", section="§7.3"),
        difficulty="easy",
        equipment_types=["aircraft_engine"],
        keywords=["BIT", "built-in test"],
    ),
    MaintQAItem(
        id="maintqa_ergo_003",
        query="What is the recommended range for the operating angle?",
        query_en="What is the recommended range for operating angle?",
        constraint_type="Ergonomics",
        constraint_type_id=6,
        answer="15°-45°",
        answer_source=AnswerSource(document="DOD-HDBK-791", section="§3.5"),
        difficulty="medium",
        equipment_types=["aircraft_engine"],
        keywords=["operating angle", "human factors engineering"],
    ),
    MaintQAItem(
        id="maintqa_time_003",
        query="What is the definition of Mmax?",
        query_en="What is the definition of Mmax?",
        constraint_type="Time Parameters",
        constraint_type_id=10,
        answer="Maximum corrective maintenance time — the upper limit of repair time at a specified confidence level",
        answer_source=AnswerSource(document="GJB 368B", section="§3.1"),
        difficulty="medium",
        equipment_types=["aircraft_engine", "naval_power"],
        keywords=["Mmax", "maximum repair time"],
    ),
    MaintQAItem(
        id="maintqa_inter_002",
        query="What is the requirement for the standardization rate?",
        query_en="What is the requirement for standardization rate?",
        constraint_type="Interchangeability",
        constraint_type_id=2,
        answer="The standardization rate of fasteners shall be ≥ 80%",
        answer_source=AnswerSource(document="GJB 368B", section="§4.6.2"),
        difficulty="medium",
        equipment_types=["aircraft_engine", "naval_power"],
        keywords=["standardization rate", "fasteners"],
    ),
]

# Save
dataset = MaintQADataset()
dataset.items = items
dataset.save("test")

print(f"✓ MaintQA dataset expanded to {len(items)} items")
print(f"✓ Saved to data/maintqa/test.jsonl")
print(f"\nStatistics:")
stats = dataset.stats()
for key, value in stats.items():
    print(f"  {key}: {value}")
